train_consumption_columns = [
                   # 'SUM_MINUTES',
                   # 'VOICE_DUR_MIN',
                   # 'DATA_VOL_MB',
                   # 'SUM_DATA_MB',
                   'SUM_DATA_MIN',
                   ]
train_feature_num_columns = [
                       'REVENUE',
                       'COM_CAT#31',
                       'COST',
                       'COM_CAT#22',
                       'COM_CAT#23',
                       # 'COM_CAT#29',
                       'COM_CAT#27',
                       # 'COM_CAT#8',
                       # 'ARPU_GROUP',
                       # 'RENT_CHANNEL',
                       'RENT_CHANNEL#22',
                       # 'COM_CAT#20',
                       'COM_CAT#17',
                       'ITC',
                       # 'ITC#32',
                       # 'COM_CAT#19',
                       # 'COM_CAT#132',
                       # 'COM_CAT#133',
                       # 'COM_CAT#232',
                       # 'COM_CAT#233',
                       # 'COM_CAT#332',
                       # 'COM_CAT#333',
                       # 'COM_CAT#832',
                       # 'COM_CAT#833',
                       #  'COM_CAT#828',
                       'ARPU_GROUP#33',
                       # 'ARPU_GROUP#32',
                        'COM_CAT#317',
                        'RENT_CHANNEL#33',
                        'ITC#33',
                        'ITC#22',
                        'ITC#32',
                        # 'ITC#1',
                        'ITC#8',
                        'ARPU_GROUP#22',
                        'ARPU_GROUP#28',
                        # 'ARPU_GROUP#1',
                        # 'ARPU_GROUP#28'
                        'VAS#28',
                        # 'COM_CAT#128',
                        # 'COM_CAT#328',
                        # 'COM_CAT#3428',
                        # 'RENT_CHANNEL#1'
                       ]
train_cat_columns = [
    # 'INTERNET_TYPE_ID_1',
    'INTERNET_TYPE_ID_2',
    'INTERNET_TYPE_ID_3',
    'DT_2G',
    'DT_3G',
    'DT_4G',
    # 'CLST_0',
    'CLST_1',
    # 'CLST_2',
    # 'CLST_3',
    # 'CLST_4',
    'CLST_5',
    # 'CLST_6',
    # 'CLST_7',
    # 'CLST_8',
    'CLST_9',
    'ACT_0',
    'BASE_TYPE_1',
    'BASE_TYPE_2',
    'DEVICE_TYPE_ID_3',
    'DEVICE_TYPE_ID_5',
    'DEVICE_TYPE_ID_4',
    'COM_CAT#1c_8',
    'COM_CAT#1c_1',
    'COM_CAT#1c_7',
    'COM_CAT#34c_5',
    'COM_CAT#34c_3',
    # 'COM_CAT#34c_8',
    'COM_CAT#34c_10',
    'ARPU_GROUPc_6',
    # 'COM_CAT#7_3',
   'COM_CAT#7_8',

    # 'SUM_DATA_MB#1',
    # 'SUM_DATA_MIN#1',
    # 'DATA_VOL_MB#22',
    'SUM_MINUTES#8',
    'VOICE_DUR_MIN#8',
    'SUM_DATA_MIN#8l',
    'SUM_DATA_MIN#34l',
    'SUM_DATA_MIN#1l',
    'SUM_DATA_MIN#22l',
    'lDATA_VOL_MB#17',
    'lDATA_VOL_MB#22',
    'SUM_MINUTES#34l',
    'SUM_MINUTES#3l',
    'lSUM_DATA_MB#28',
    'lSUM_DATA_MB#22',
    'SUM_DATA_MIN#2',
    # 'lSUM_DATA_MIN#2',
    'lDATA_VOL_MB#28',
    # 'SUM_MINUTES_4',
    # 'SUM_DATA_MIN_1',
    # 'VOICE_DUR_MIN_9',
    # 'DATA_VOL_MB_7'
    # 'mSM_VO4',
    # 'dSM_VO1',
    # 'dSM_VO3',
    # 'RATE_7',
    # 'mSM_VO9'
    # 'VOICE_DUR_MIN_5#22',
    # 'VOICE_DUR_MIN_9#33',
    # 'SUM_DATA_MIN_9#33',
    # 'DATA_VOL_MB_7#1',
    # 'SUM_MINUTES_4#32'
    # 'SUM_MINUTES_4#28'
    # 'SUM_MINUTES_4#3',
    # 'SUM_DATA_MIN_1#3'
]
train_qa_columns = [
                    'QA',
                    # 'QA0',
                    'QA1'
                    # 'QA01',
                    # 'PSSR_2G_COUNT',
                    ]
train_rate_columns = [
                    'RATE_2G',
                    'RATE_3G',
                    'RATE_4G',
                    ]
train_columns_kpi = [
    # 'CELL_AVAILABILITY_2G',
    # 'CELL_AVAILABILITY_3G',
    # 'CELL_AVAILABILITY_4G',
    # 'CSSR_2G',
    'CSSR_3G',
    # 'ERAB_PS_BLOCKING_RATE_LTE',
    # 'ERAB_PS_BLOCKING_RATE_PLMN_LTE',
    # 'ERAB_PS_DROP_RATE_LTE',
    # 'HSPDSCH_CODE_UTIL_3G',
    # 'NODEB_CNBAP_LOAD_HARDWARE',
    # 'PART_CQI_QPSK_LTE',
    # 'PART_MCS_QPSK_LTE',
    # 'PROC_LOAD_3G',
    # 'PSSR_2G',
    # 'PSSR_3G',
    # 'PSSR_LTE',
    # 'RAB_CS_BLOCKING_RATE_3G',
    'RAB_CS_DROP_RATE_3G',
    'RAB_PS_BLOCKING_RATE_3G',
    'RAB_PS_DROP_RATE_3G',
    # 'RBU_AVAIL_DL',
    # 'RBU_AVAIL_DL_LTE',
    # 'RBU_AVAIL_UL',
    # 'RBU_OTHER_DL',
    # 'RBU_OTHER_UL',
    # 'RBU_OWN_DL',
    # 'RBU_OWN_UL',
    # 'RRC_BLOCKING_RATE_3G',
    # 'RRC_BLOCKING_RATE_LTE',
    # 'RTWP_3G',
    # 'SHO_FACTOR',
    # 'TBF_DROP_RATE_2G',
    # 'TCH_DROP_RATE_2G',
    # 'UTIL_BRD_CPU_3G',
    # 'UTIL_CE_DL_3G',
    # 'UTIL_CE_HW_DL_3G',
    # 'UTIL_CE_UL_3G',
    # 'UTIL_SUBUNITS_3G',
    # 'UL_VOLUME_LTE',
    # 'DL_VOLUME_LTE',
    'TOTAL_DL_VOLUME_3G',
    'TOTAL_UL_VOLUME_3G'
]

train_columns_chnn = [
    # 'AVEUSERNUMBER',
    # 'AVEUSERNUMBER_PLMN',
    # 'AVR_DL_HSPA_USER_3G',
    # 'AVR_DL_R99_USER_3G',
    # 'AVR_DL_USER_3G',
    # 'AVR_DL_USER_LTE',
    # 'AVR_TX_POWER_3G',
    'AVR_UL_HSPA_USER',
    # 'AVR_UL_R99_USER',
    # 'AVR_UL_USER_3G',
    # 'AVR_UL_USER_LTE',
    'DL_AVR_THROUGHPUT_3G',
    # 'DL_AVR_THROUGHPUT_LTE',
    # 'DL_AVR_THROUGHPUT_R99',
    # 'DL_MEAN_USER_THROUGHPUT_LTE',
    # 'DL_MEAN_USER_THROUGHPUT_DL_2G',
    'DL_MEAN_USER_THROUGHPUT_HSPA3G',
    # 'DL_MEAN_USER_THROUGHPUT_PLTE',
    'DL_MEAN_USER_THROUGHPUT_REL93G',
    # 'HSDPA_USERS_3G',
    # 'HSUPA_USERS_3G',
    # 'RBU_USED_DL',
    # 'RBU_USED_UL',
    # 'RELATIVE_RBU_USED_DL',
    # 'RELATIVE_RBU_USED_UL',
    # 'RELATIVE_TX_POWER_3G',
    # 'UL_AVR_THROUGHPUT_3G',
    # 'UL_AVR_THROUGHPUT_LTE',
    # 'UL_AVR_THROUGHPUT_R99',
    # 'UL_MEAN_USER_THROUGHPUT_LTE',
    # 'UL_MEAN_USER_THROUGHPUT_HS3G',
    # 'UL_MEAN_USER_THROUGHPUT_PLTE',
    'UL_MEAN_USER_THROUGHPUT_REL93G'
]

train_columns = train_consumption_columns\
                + train_feature_num_columns\
                + train_cat_columns \
                + train_rate_columns \
                + train_columns_kpi \
                + train_columns_chnn

cat_columns = [
    'CLST_0',
    'CLST_1',
    'CLST_2',
    'CLST_3',
    'CLST_4',
    'CLST_5',
    'CLST_6',
    'CLST_7',
    'CLST_8',
    'CLST_9',
    # 'COM_CAT#1',
    # 'COM_CAT#2',
    # 'COM_CAT#3',
    # 'COM_CAT#34',
]